"""empty message

Revision ID: 6ac1a2113078
Revises: 97480c5ef5ee
Create Date: 2022-06-01 22:18:00.560147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac1a2113078'
down_revision = '97480c5ef5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
