"""empty message

Revision ID: 97480c5ef5ee
Revises: da8931ea92b6
Create Date: 2022-06-01 21:33:06.466315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97480c5ef5ee'
down_revision = 'da8931ea92b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
