"""empty message

Revision ID: da8931ea92b6
Revises: 39cca99be2cc
Create Date: 2022-06-01 21:14:34.156570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8931ea92b6'
down_revision = '39cca99be2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(), nullable=True))
    op.drop_column('venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
